# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace

#$font = FreeSans Bold
$font = Trebuchet MS #--> Trebuchet MS is also the Microsoft's font
$white = rgb(dddddd)
$black = rgb(111111)

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    path = $HOME/Images/animeirl.jpg
    blur_passes = 0
}

input-field {
    size = 20%, 5%
    outline_thickness = 0
    inner_color = rgba(0, 0, 0, 0)
    outer_color = rgba(0, 0, 0, 0)
    check_color = rgba(0, 0, 0, 0)
    fail_color = rgba(0, 0, 0, 0)

    font_color = $white
    fade_on_empty = true
    rounding = 5

    font_family = $font
    placeholder_text = 
    fail_text = Terminated.

    # uncomment to use a letter instead of a dot to indicate the typed password
    #dots_text_format = *
    #dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    #hide_input = true

    position = 0, 100
    halign = center
    valign = bottom
}

# TIME
label {
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 20
    color = $white
    font_family = $font

    position = 0, 0
    halign = right
    valign = top
}

# DATE
label {
    text = cmd[update:60000] date +" %d.%m.%Y" # update every 60 seconds
    font_size = 15
    color = $white
    font_family = $font

    position = 0, -30
    halign = right
    valign = top
}

# LANG
label {
    text = $LAYOUT[English (US),Russian]
    font_family = $font
    color = $white
    font_size = 10
   #onclick = hyprctl switchxkblayout all next

    position = 0, -55
    halign = right
    valign = top
}

#label {
#    font_size = 17
#    font_family = $font
#    color = $white
#    text = cmd[update:60000] echo "$(bash .config/hypr/welcome.sh)"
#    position = 0, 30
#    halign = center
#    valign = bottom
#}


#image {
#    path = /home/richard/Images/hunk_monitor.jpg
#    size = 100
#    border_size = 2
#    border_color = rgb(ffffff)
#    position = 0, -100
#    halign = center
#    valign = center
#}
