# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = FreeSans Bold #JetBrainsMono Nerd Font Mono
$white = rgb(dddddd)

general {
    hide_cursor = true
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    path = $HOME/Images/Black_mesa_black.jpg
    blur_passes = 0
}

input-field {
    size = 20%, 5%
    outline_thickness = 1
    inner_color = rgba(0, 0, 0, 0)

    outer_color = $white
    check_color = $white
    fail_color = $white

    font_color = $white
    fade_on_empty = true
    rounding = 0

    font_family = $font
    placeholder_text = ...
    fail_text = Forgot something? #$PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    #dots_text_format = *
    #dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    #hide_input = true

    position = 0, 100
    halign = center
    valign = bottom
}

# TIME
label {
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 15
    color = $white
    font_family = $font

    position = -120, 0
    halign = right
    valign = top
}

# DATE
label {
    text = cmd[update:60000] date +"| %d.%m.%Y" # update every 60 seconds
    font_size = 15
    color = $white
    font_family = $font

    position = 0, 0
    halign = right
    valign = top
}

# LANG
label {
    text = $LAYOUT[English (US),Russian]
    font_family = $font
    color = $white
    font_size = 10
   #onclick = hyprctl switchxkblayout all next

    position = 0, -25
    halign = right
    valign = top
}

label {
    font_size = 15
    font_family = $font
    color = $white
    text = cmd[update:60000] echo "$(bash .config/hypr/welcome.sh)"
    position = 0, 30
    halign = center
    valign = bottom
}

# Profile Picture
#image {
#    path = /home/richard/Images/gman.jpg
#    size = 100
#    border_size = 2
#    border_color = rgb(ffffff)
#    position = 0, -100
#    halign = center
#    valign = center
#}
